/** Auto-generated world country list (7 continents). Do not edit by hand — regenerate via scripts. */
export type WorldContinent = 'AF' | 'AS' | 'EU' | 'NA' | 'SA' | 'OC' | 'AN';

export type WorldCountry = {
  code: string;
  en: string;
  ar: string;
  continent: WorldContinent;
};

export const WORLD_COUNTRIES: readonly WorldCountry[] = [
  { code: "EG", en: "Egypt", ar: "مصر", continent: "AF" },
  { code: "DZ", en: "Algeria", ar: "الجزائر", continent: "AF" },
  { code: "AO", en: "Angola", ar: "أنغولا", continent: "AF" },
  { code: "BJ", en: "Benin", ar: "بنين", continent: "AF" },
  { code: "BW", en: "Botswana", ar: "بوتسوانا", continent: "AF" },
  { code: "BF", en: "Burkina Faso", ar: "بوركينا فاسو", continent: "AF" },
  { code: "BI", en: "Burundi", ar: "بوروندي", continent: "AF" },
  { code: "CV", en: "Cabo Verde", ar: "الرأس الأخضر", continent: "AF" },
  { code: "CM", en: "Cameroon", ar: "الكاميرون", continent: "AF" },
  { code: "CF", en: "Central African Republic", ar: "جمهورية أفريقيا الوسطى", continent: "AF" },
  { code: "TD", en: "Chad", ar: "تشاد", continent: "AF" },
  { code: "KM", en: "Comoros", ar: "جزر القمر", continent: "AF" },
  { code: "CG", en: "Congo", ar: "الكونغو", continent: "AF" },
  { code: "CD", en: "Congo (DRC)", ar: "جمهورية الكونغو الديمقراطية", continent: "AF" },
  { code: "CI", en: "Côte d'Ivoire", ar: "ساحل العاج", continent: "AF" },
  { code: "DJ", en: "Djibouti", ar: "جيبوتي", continent: "AF" },
  { code: "GQ", en: "Equatorial Guinea", ar: "غينيا الاستوائية", continent: "AF" },
  { code: "ER", en: "Eritrea", ar: "إريتريا", continent: "AF" },
  { code: "SZ", en: "Eswatini", ar: "إسواتيني", continent: "AF" },
  { code: "ET", en: "Ethiopia", ar: "إثيوبيا", continent: "AF" },
  { code: "GA", en: "Gabon", ar: "الغابون", continent: "AF" },
  { code: "GM", en: "Gambia", ar: "غامبيا", continent: "AF" },
  { code: "GH", en: "Ghana", ar: "غانا", continent: "AF" },
  { code: "GN", en: "Guinea", ar: "غينيا", continent: "AF" },
  { code: "GW", en: "Guinea-Bissau", ar: "غينيا بيساو", continent: "AF" },
  { code: "KE", en: "Kenya", ar: "كينيا", continent: "AF" },
  { code: "LS", en: "Lesotho", ar: "ليسوتو", continent: "AF" },
  { code: "LR", en: "Liberia", ar: "ليبيريا", continent: "AF" },
  { code: "LY", en: "Libya", ar: "ليبيا", continent: "AF" },
  { code: "MG", en: "Madagascar", ar: "مدغشقر", continent: "AF" },
  { code: "MW", en: "Malawi", ar: "ملاوي", continent: "AF" },
  { code: "ML", en: "Mali", ar: "مالي", continent: "AF" },
  { code: "MR", en: "Mauritania", ar: "موريتانيا", continent: "AF" },
  { code: "MU", en: "Mauritius", ar: "موريشيوس", continent: "AF" },
  { code: "MA", en: "Morocco", ar: "المغرب", continent: "AF" },
  { code: "MZ", en: "Mozambique", ar: "موزمبيق", continent: "AF" },
  { code: "NA", en: "Namibia", ar: "ناميبيا", continent: "AF" },
  { code: "NE", en: "Niger", ar: "النيجر", continent: "AF" },
  { code: "NG", en: "Nigeria", ar: "نيجيريا", continent: "AF" },
  { code: "RW", en: "Rwanda", ar: "رواندا", continent: "AF" },
  { code: "ST", en: "Sao Tome and Principe", ar: "ساو تومي وبرينسيبي", continent: "AF" },
  { code: "SN", en: "Senegal", ar: "السنغال", continent: "AF" },
  { code: "SC", en: "Seychelles", ar: "سيشل", continent: "AF" },
  { code: "SL", en: "Sierra Leone", ar: "سيراليون", continent: "AF" },
  { code: "SO", en: "Somalia", ar: "الصومال", continent: "AF" },
  { code: "ZA", en: "South Africa", ar: "جنوب أفريقيا", continent: "AF" },
  { code: "SS", en: "South Sudan", ar: "جنوب السودان", continent: "AF" },
  { code: "SD", en: "Sudan", ar: "السودان", continent: "AF" },
  { code: "TZ", en: "Tanzania", ar: "تنزانيا", continent: "AF" },
  { code: "TG", en: "Togo", ar: "توغو", continent: "AF" },
  { code: "TN", en: "Tunisia", ar: "تونس", continent: "AF" },
  { code: "UG", en: "Uganda", ar: "أوغندا", continent: "AF" },
  { code: "ZM", en: "Zambia", ar: "زامبيا", continent: "AF" },
  { code: "ZW", en: "Zimbabwe", ar: "زيمبابوي", continent: "AF" },
  { code: "AF", en: "Afghanistan", ar: "أفغانستان", continent: "AS" },
  { code: "AM", en: "Armenia", ar: "أرمينيا", continent: "AS" },
  { code: "AZ", en: "Azerbaijan", ar: "أذربيجان", continent: "AS" },
  { code: "BH", en: "Bahrain", ar: "البحرين", continent: "AS" },
  { code: "BD", en: "Bangladesh", ar: "بنغلاديش", continent: "AS" },
  { code: "BT", en: "Bhutan", ar: "بوتان", continent: "AS" },
  { code: "BN", en: "Brunei", ar: "بروناي", continent: "AS" },
  { code: "KH", en: "Cambodia", ar: "كمبوديا", continent: "AS" },
  { code: "CN", en: "China", ar: "الصين", continent: "AS" },
  { code: "CY", en: "Cyprus", ar: "قبرص", continent: "AS" },
  { code: "GE", en: "Georgia", ar: "جورجيا", continent: "AS" },
  { code: "IN", en: "India", ar: "الهند", continent: "AS" },
  { code: "ID", en: "Indonesia", ar: "إندونيسيا", continent: "AS" },
  { code: "IR", en: "Iran", ar: "إيران", continent: "AS" },
  { code: "IQ", en: "Iraq", ar: "العراق", continent: "AS" },
  { code: "IL", en: "Israel", ar: "إسرائيل", continent: "AS" },
  { code: "JP", en: "Japan", ar: "اليابان", continent: "AS" },
  { code: "JO", en: "Jordan", ar: "الأردن", continent: "AS" },
  { code: "KZ", en: "Kazakhstan", ar: "كازاخستان", continent: "AS" },
  { code: "KW", en: "Kuwait", ar: "الكويت", continent: "AS" },
  { code: "KG", en: "Kyrgyzstan", ar: "قيرغيزستان", continent: "AS" },
  { code: "LA", en: "Laos", ar: "لاوس", continent: "AS" },
  { code: "LB", en: "Lebanon", ar: "لبنان", continent: "AS" },
  { code: "MY", en: "Malaysia", ar: "ماليزيا", continent: "AS" },
  { code: "MV", en: "Maldives", ar: "المالديف", continent: "AS" },
  { code: "MN", en: "Mongolia", ar: "منغوليا", continent: "AS" },
  { code: "MM", en: "Myanmar", ar: "ميانمار", continent: "AS" },
  { code: "NP", en: "Nepal", ar: "نيبال", continent: "AS" },
  { code: "KP", en: "North Korea", ar: "كوريا الشمالية", continent: "AS" },
  { code: "OM", en: "Oman", ar: "عُمان", continent: "AS" },
  { code: "PK", en: "Pakistan", ar: "باكستان", continent: "AS" },
  { code: "PS", en: "Palestine", ar: "فلسطين", continent: "AS" },
  { code: "PH", en: "Philippines", ar: "الفلبين", continent: "AS" },
  { code: "QA", en: "Qatar", ar: "قطر", continent: "AS" },
  { code: "SA", en: "Saudi Arabia", ar: "السعودية", continent: "AS" },
  { code: "SG", en: "Singapore", ar: "سنغافورة", continent: "AS" },
  { code: "KR", en: "South Korea", ar: "كوريا الجنوبية", continent: "AS" },
  { code: "LK", en: "Sri Lanka", ar: "سريلانكا", continent: "AS" },
  { code: "SY", en: "Syria", ar: "سوريا", continent: "AS" },
  { code: "TW", en: "Taiwan", ar: "تايوان", continent: "AS" },
  { code: "TJ", en: "Tajikistan", ar: "طاجيكستان", continent: "AS" },
  { code: "TH", en: "Thailand", ar: "تايلاند", continent: "AS" },
  { code: "TL", en: "Timor-Leste", ar: "تيمور الشرقية", continent: "AS" },
  { code: "TR", en: "Turkey", ar: "تركيا", continent: "AS" },
  { code: "TM", en: "Turkmenistan", ar: "تركمانستان", continent: "AS" },
  { code: "AE", en: "United Arab Emirates", ar: "الإمارات", continent: "AS" },
  { code: "UZ", en: "Uzbekistan", ar: "أوزبكستان", continent: "AS" },
  { code: "VN", en: "Vietnam", ar: "فيتنام", continent: "AS" },
  { code: "YE", en: "Yemen", ar: "اليمن", continent: "AS" },
  { code: "AL", en: "Albania", ar: "ألبانيا", continent: "EU" },
  { code: "AD", en: "Andorra", ar: "أندورا", continent: "EU" },
  { code: "AT", en: "Austria", ar: "النمسا", continent: "EU" },
  { code: "BY", en: "Belarus", ar: "بيلاروس", continent: "EU" },
  { code: "BE", en: "Belgium", ar: "بلجيكا", continent: "EU" },
  { code: "BA", en: "Bosnia and Herzegovina", ar: "البوسنة والهرسك", continent: "EU" },
  { code: "BG", en: "Bulgaria", ar: "بلغاريا", continent: "EU" },
  { code: "HR", en: "Croatia", ar: "كرواتيا", continent: "EU" },
  { code: "CZ", en: "Czechia", ar: "التشيك", continent: "EU" },
  { code: "DK", en: "Denmark", ar: "الدنمارك", continent: "EU" },
  { code: "EE", en: "Estonia", ar: "إستونيا", continent: "EU" },
  { code: "FI", en: "Finland", ar: "فنلندا", continent: "EU" },
  { code: "FR", en: "France", ar: "فرنسا", continent: "EU" },
  { code: "DE", en: "Germany", ar: "ألمانيا", continent: "EU" },
  { code: "GR", en: "Greece", ar: "اليونان", continent: "EU" },
  { code: "HU", en: "Hungary", ar: "المجر", continent: "EU" },
  { code: "IS", en: "Iceland", ar: "أيسلندا", continent: "EU" },
  { code: "IE", en: "Ireland", ar: "أيرلندا", continent: "EU" },
  { code: "IT", en: "Italy", ar: "إيطاليا", continent: "EU" },
  { code: "XK", en: "Kosovo", ar: "كوسوفو", continent: "EU" },
  { code: "LV", en: "Latvia", ar: "لاتفيا", continent: "EU" },
  { code: "LI", en: "Liechtenstein", ar: "ليختنشتاين", continent: "EU" },
  { code: "LT", en: "Lithuania", ar: "ليتوانيا", continent: "EU" },
  { code: "LU", en: "Luxembourg", ar: "لوكسمبورغ", continent: "EU" },
  { code: "MT", en: "Malta", ar: "مالطا", continent: "EU" },
  { code: "MD", en: "Moldova", ar: "مولدوفا", continent: "EU" },
  { code: "MC", en: "Monaco", ar: "موناكو", continent: "EU" },
  { code: "ME", en: "Montenegro", ar: "الجبل الأسود", continent: "EU" },
  { code: "NL", en: "Netherlands", ar: "هولندا", continent: "EU" },
  { code: "MK", en: "North Macedonia", ar: "مقدونيا الشمالية", continent: "EU" },
  { code: "NO", en: "Norway", ar: "النرويج", continent: "EU" },
  { code: "PL", en: "Poland", ar: "بولندا", continent: "EU" },
  { code: "PT", en: "Portugal", ar: "البرتغال", continent: "EU" },
  { code: "RO", en: "Romania", ar: "رومانيا", continent: "EU" },
  { code: "RU", en: "Russia", ar: "روسيا", continent: "EU" },
  { code: "SM", en: "San Marino", ar: "سان مارينو", continent: "EU" },
  { code: "RS", en: "Serbia", ar: "صربيا", continent: "EU" },
  { code: "SK", en: "Slovakia", ar: "سلوفاكيا", continent: "EU" },
  { code: "SI", en: "Slovenia", ar: "سلوفينيا", continent: "EU" },
  { code: "ES", en: "Spain", ar: "إسبانيا", continent: "EU" },
  { code: "SE", en: "Sweden", ar: "السويد", continent: "EU" },
  { code: "CH", en: "Switzerland", ar: "سويسرا", continent: "EU" },
  { code: "UA", en: "Ukraine", ar: "أوكرانيا", continent: "EU" },
  { code: "GB", en: "United Kingdom", ar: "المملكة المتحدة", continent: "EU" },
  { code: "VA", en: "Vatican City", ar: "الفاتيكان", continent: "EU" },
  { code: "AG", en: "Antigua and Barbuda", ar: "أنتيغوا وباربودا", continent: "NA" },
  { code: "BS", en: "Bahamas", ar: "الباهاما", continent: "NA" },
  { code: "BB", en: "Barbados", ar: "باربادوس", continent: "NA" },
  { code: "BZ", en: "Belize", ar: "بليز", continent: "NA" },
  { code: "CA", en: "Canada", ar: "كندا", continent: "NA" },
  { code: "CR", en: "Costa Rica", ar: "كوستاريكا", continent: "NA" },
  { code: "CU", en: "Cuba", ar: "كوبا", continent: "NA" },
  { code: "DM", en: "Dominica", ar: "دومينيكا", continent: "NA" },
  { code: "DO", en: "Dominican Republic", ar: "جمهورية الدومينيكان", continent: "NA" },
  { code: "SV", en: "El Salvador", ar: "السلفادور", continent: "NA" },
  { code: "GD", en: "Grenada", ar: "غرينادا", continent: "NA" },
  { code: "GT", en: "Guatemala", ar: "غواتيمالا", continent: "NA" },
  { code: "HT", en: "Haiti", ar: "هايتي", continent: "NA" },
  { code: "HN", en: "Honduras", ar: "هندوراس", continent: "NA" },
  { code: "JM", en: "Jamaica", ar: "جامايكا", continent: "NA" },
  { code: "MX", en: "Mexico", ar: "المكسيك", continent: "NA" },
  { code: "NI", en: "Nicaragua", ar: "نيكاراغوا", continent: "NA" },
  { code: "PA", en: "Panama", ar: "بنما", continent: "NA" },
  { code: "KN", en: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس", continent: "NA" },
  { code: "LC", en: "Saint Lucia", ar: "سانت لوسيا", continent: "NA" },
  { code: "VC", en: "Saint Vincent and the Grenadines", ar: "سانت فينسنت والغرينادين", continent: "NA" },
  { code: "TT", en: "Trinidad and Tobago", ar: "ترينيداد وتوباغو", continent: "NA" },
  { code: "US", en: "United States", ar: "الولايات المتحدة", continent: "NA" },
  { code: "AR", en: "Argentina", ar: "الأرجنتين", continent: "SA" },
  { code: "BO", en: "Bolivia", ar: "بوليفيا", continent: "SA" },
  { code: "BR", en: "Brazil", ar: "البرازيل", continent: "SA" },
  { code: "CL", en: "Chile", ar: "تشيلي", continent: "SA" },
  { code: "CO", en: "Colombia", ar: "كولومبيا", continent: "SA" },
  { code: "EC", en: "Ecuador", ar: "الإكوادور", continent: "SA" },
  { code: "GY", en: "Guyana", ar: "غيانا", continent: "SA" },
  { code: "PY", en: "Paraguay", ar: "باراغواي", continent: "SA" },
  { code: "PE", en: "Peru", ar: "بيرو", continent: "SA" },
  { code: "SR", en: "Suriname", ar: "سورينام", continent: "SA" },
  { code: "UY", en: "Uruguay", ar: "أوروغواي", continent: "SA" },
  { code: "VE", en: "Venezuela", ar: "فنزويلا", continent: "SA" },
  { code: "AU", en: "Australia", ar: "أستراليا", continent: "OC" },
  { code: "FJ", en: "Fiji", ar: "فيجي", continent: "OC" },
  { code: "KI", en: "Kiribati", ar: "كيريباتي", continent: "OC" },
  { code: "MH", en: "Marshall Islands", ar: "جزر مارشال", continent: "OC" },
  { code: "FM", en: "Micronesia", ar: "ميكرونيزيا", continent: "OC" },
  { code: "NR", en: "Nauru", ar: "ناورو", continent: "OC" },
  { code: "NZ", en: "New Zealand", ar: "نيوزيلندا", continent: "OC" },
  { code: "PW", en: "Palau", ar: "بالاو", continent: "OC" },
  { code: "PG", en: "Papua New Guinea", ar: "بابوا غينيا الجديدة", continent: "OC" },
  { code: "WS", en: "Samoa", ar: "ساموا", continent: "OC" },
  { code: "SB", en: "Solomon Islands", ar: "جزر سليمان", continent: "OC" },
  { code: "TO", en: "Tonga", ar: "تونغا", continent: "OC" },
  { code: "TV", en: "Tuvalu", ar: "توفالو", continent: "OC" },
  { code: "VU", en: "Vanuatu", ar: "فانواتو", continent: "OC" },
  { code: "AQ", en: "Antarctica", ar: "القارة القطبية الجنوبية", continent: "AN" },
] as const;

export const PATIENT_COUNTRY_CODES = WORLD_COUNTRIES.map((c) => c.code) as readonly string[];

export type PatientCountryCode = string;

export const PATIENT_COUNTRY_LABELS: Record<string, { en: string; ar: string }> =
  Object.fromEntries(WORLD_COUNTRIES.map((c) => [c.code, { en: c.en, ar: c.ar }]));

export const CONTINENT_LABELS: Record<WorldContinent, { en: string; ar: string }> = {
  AF: { en: 'Africa', ar: 'أفريقيا' },
  AS: { en: 'Asia', ar: 'آسيا' },
  EU: { en: 'Europe', ar: 'أوروبا' },
  NA: { en: 'North America', ar: 'أمريكا الشمالية' },
  SA: { en: 'South America', ar: 'أمريكا الجنوبية' },
  OC: { en: 'Oceania', ar: 'أوقيانوسيا' },
  AN: { en: 'Antarctica', ar: 'أنتاركتيكا' },
};

